server:
  port: 8112

spring:
  application:
    name: service-influxdb-app
  resources:
    static-locations: classpath:/static
  freemarker:
    template-loader-path: classpath:/static
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .html

aaa:
  host: ${INFLUXDB_HOST:172.21.81.42}
  port: ${INFLUXDB_PORT:31639}
  uri: ${INFLUXDB_URI:http://172.21.81.42:31639}
  db: ${INFLUXDB_DB:lz}
  username: ${INFLUXDB_USERNAME:u1}
  password: ${INFLUXDB_PASSWORD:GAN68rfhzvvNSmdGAAWeR9JgC}