---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-tp
spec:
  selector:
    matchLabels:
      app: springcloud-service-tp

  replicas: 1

  template:
    metadata:
      labels:
        app: springcloud-service-tp
    spec:
      containers:
       - name: service-tp-instance
         image: registry.cn-hangzhou.aliyuncs.com/magiclian/service-tp:v3
         env:
         - name: EUREKA_URL
           value: eureka-server
         ports:
         - containerPort: 8763


---
kind: Service
apiVersion: v1
metadata:
  name: service-tp
spec:
  selector:
    app: springcloud-service-tp
  ports:
  - protocol: TCP
    port: 8763
    targetPort: 8763
  #type: NodePort


