server:
  port: 8762

spring:
  application:
    name: service-zuul

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka

zuul:
  routes:
    service-tp:
      path: /service-tp/**
      serviceId: service-tp
    service-api:
      path: /service-api/**
      serviceId: service-api

