server:
  port: 8764

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka

spring:
  application:
    name: service-api
